import React from 'react';
import {Home,Search,Library,Compass,Heart,Play,Pause,SkipBack,SkipForward,Shuffle,Repeat,MoreHorizontal,ChevronDown,ListMusic,AudioLines,MonitorSpeaker,SlidersHorizontal,X,Trash2,Music2} from 'lucide-react';

function HomeView({hero,allTracks,play,liked,like}){return <section><div className="hero"><div className="hero-bg" style={{backgroundImage:`url(${hero.artwork})`}}/><div className="hero-copy"><span className="eyebrow">AURALIS SELECTS</span><h1>Music, with atmosphere.</h1><p>Discover, play and keep your music in one beautifully controlled space.</p><button className="primary-btn" onClick={()=>play(hero)}><Play size={17} fill="currentColor"/> Start listening</button></div></div><Section title="Quick Picks" tracks={allTracks.slice(0,4)} play={play} liked={liked} like={like}/><Section title="Recently Played" tracks={allTracks.slice(0,6)} play={play} liked={liked} like={like}/><Section title="Made For You" tracks={[...allTracks].reverse().slice(0,6)} play={play} liked={liked} like={like}/></section>}

function Section({title,tracks,play,liked,like}){return <div className="section"><div className="section-head"><h2>{title}</h2><button>See all</button></div><TrackRow tracks={tracks} play={play} liked={liked} like={like}/></div>}

function TrackRow({tracks,play,liked,like}){return <div className="track-row">{tracks.map(t=><TrackCard key={t.id} t={t} play={play} liked={liked} like={like}/>)}</div>}

function TrackGrid({tracks,play,liked,like,local,remove}){if(!tracks.length)return <Empty icon={Music2} title="Nothing here yet" text="Your saved and imported music will appear here."/>;return <div className="track-grid">{tracks.map(t=><TrackCard key={t.id} t={t} play={play} liked={liked} like={like} local={local} remove={remove}/>)}</div>}

function TrackCard({t,play,liked,like,local,remove}){return <article className="track-card"><div className="cover" style={t.artwork?{backgroundImage:`url(${t.artwork})`}:undefined}><span className="cover-fallback"><AudioLines size={28}/></span><button className="cover-play" onClick={()=>play(t)} aria-label={`Play ${t.title}`}><Play size={20} fill="currentColor"/></button></div><div className="card-info"><div className="card-title" title={t.title}>{t.title}</div><div className="card-artist">{t.artist}</div><div className="card-meta">{t.source==='local'?'LOCAL':'YOUTUBE'} {t.source==='local'?'· FILE':'· MUSIC'}</div></div><button className={'like-btn '+(liked.includes(t.id)?'liked':'')} onClick={()=>like(t)}><Heart size={17} fill={liked.includes(t.id)?'currentColor':'none'}/></button>{local&&<button className="delete-btn" onClick={()=>remove(t.id)} aria-label="Delete local track"><Trash2 size={16}/></button>}</article>}

function MiniPlayer({current,playing,setPlaying,like,liked,open,next}){return <div className="mini-player"><button className="mini-art" onClick={open} style={current.artwork?{backgroundImage:`url(${current.artwork})`}:undefined}><span>{!current.artwork&&<AudioLines size={18}/>}</span></button><div className="mini-info" onClick={open}><b>{current.title}</b><span>{current.artist}</span></div><button className="icon-btn" onClick={()=>like(current)}><Heart size={18} fill={liked.includes(current.id)?'currentColor':'none'}/></button><button className="icon-btn mini-play" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}</button><button className="icon-btn" onClick={next}><SkipForward size={19}/></button></div>}

function FullPlayer(p){return <div className="player-overlay"><div className="player-atmos" style={p.current.artwork?{backgroundImage:`url(${p.current.artwork})`}:undefined}/><div className="full-player"><div className="player-top"><button className="icon-btn" onClick={p.close}><ChevronDown/></button><span>NOW PLAYING</span><button className="icon-btn"><MoreHorizontal/></button></div><div className="hero-art" style={p.current.artwork?{backgroundImage:`url(${p.current.artwork})`}:undefined}><span>{!p.current.artwork&&<AudioLines size={54}/>}</span></div><div className="now-meta"><div><h2>{p.current.title}</h2><p>{p.current.artist}</p><small><span>LOSSLESS READY</span> · {p.current.source==='local'?'LOCAL FILE':'YOUTUBE'}</small></div><button className={'icon-btn '+(p.liked.includes(p.current.id)?'liked':'')} onClick={()=>p.like(p.current)}><Heart fill={p.liked.includes(p.current.id)?'currentColor':'none'}/></button></div><div className="seek"><input type="range" min="0" max={Math.max(p.duration,1)} step="0.1" value={Math.min(p.progress,p.duration||1)} onChange={e=>p.seek(Number(e.target.value))}/><div><span>{fmt(p.progress)}</span><span>{fmt(p.duration)}</span></div></div><div className="main-controls"><button className={p.shuffle?'control-on':''} onClick={()=>p.setShuffle(!p.shuffle)}><Shuffle/></button><button onClick={p.prev}><SkipBack fill="currentColor"/></button><button className="play-main" onClick={()=>p.setPlaying(v=>!v)}>{p.playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button onClick={p.next}><SkipForward fill="currentColor"/></button><button className={p.repeat?'control-on':''} onClick={()=>p.setRepeat(!p.repeat)}><Repeat/></button></div><div className="player-tools"><button onClick={p.openLyrics}><ListMusic/>Lyrics</button><button onClick={p.openQueue}><ListMusic/>Queue</button><button onClick={p.openAudio}><SlidersHorizontal/>Audio</button><button><MonitorSpeaker/>Devices</button></div><div className="yt-inline"><span>YouTube playback source</span><span>Playback controls remain inside the embedded player.</span></div></div></div>}

function QueueContent({queue,current,play,setQueue}){return <div className="queue-list">{queue.length===0?<Empty icon={ListMusic} title="Queue is empty" text="Play a track to build your queue."/>:queue.map((t,i)=><div className={'queue-item '+(current?.id===t.id?'now':'')} key={t.id}><span className="queue-num">{i+1}</span><div className="queue-thumb" style={t.artwork?{backgroundImage:`url(${t.artwork})`}:undefined}><AudioLines size={14}/></div><div className="queue-text"><b>{t.title}</b><span>{t.artist}</span></div><button className="icon-btn" onClick={()=>play(t)}><Play size={16}/></button><button className="icon-btn" onClick={()=>setQueue(queue.filter(x=>x.id!==t.id))}><X size={16}/></button></div>)}</div>}

function Drawer({title,close,children}){return <div className="drawer-wrap" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>{title}</h2><button className="icon-btn" onClick={close}><X/></button></div>{children}</aside></div>}

function AudioPanel({volume,setVolume,speed,setSpeed}){return <div className="audio-panel"><label>Volume <b>{Math.round(volume*100)}%</b></label><input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/><div className="quality-card"><b>Audio quality</b><span>Auto · Source quality</span><span>Lossless-ready metadata</span></div><label>Playback speed</label><div className="speed-row">{[.75,1,1.25,1.5,2].map(x=><button className={speed===x?'selected':''} onClick={()=>setSpeed(x)} key={x}>{x}×</button>)}</div><div className="settings-list"><div><b>Crossfade</b><span>Ready for provider/backend integration</span></div><div><b>Loudness normalization</b><span>Architecture-ready</span></div><div><b>Equalizer</b><span>10-band UI can be connected to native DSP</span></div></div></div>}

function PageTitle({title,sub}){return <div className="page-title"><div><span className="eyebrow">AURALIS</span><h1>{title}</h1><p>{sub}</p></div></div>}

function Empty({icon:Icon,title,text}){return <div className="empty"><Icon size={28}/><h3>{title}</h3><p>{text}</p></div>}

function Skeleton(){return <div className="skeleton-grid">{Array.from({length:8},(_,i)=><div className="sk" key={i}/>)}</div>}

function fmt(n){if(!Number.isFinite(n)||n<=0)return '0:00';const m=Math.floor(n/60),s=Math.floor(n%60);return `${m}:${String(s).padStart(2,'0')}`}


export {HomeView,Section,TrackRow,TrackGrid,TrackCard,MiniPlayer,FullPlayer,QueueContent,Drawer,AudioPanel,PageTitle,Empty,Skeleton,fmt};
